### ISSUE TITLE
运行时显示“No 'Access-Control-Allow-Origin”

### ISSUE THREAD

**Issue by ALLJISAN** [webxoss/wixoss-fetch#3]
运行fetchWXBox("WXK09",1,50)（类似命令）时：
`Access to fetch at 'https://www.takaratomy.co.jp/products/wixoss/card/card_list.php?card=card_detail&card_no=WXK09-038' (redirected from 'http://www.takaratomy.co.jp/products/wixoss/card/card_list.php?card=card_detail&card_no=WXK09-038') from origin 'chrome-extension://cjokkigdlbpakpaffnafbhjoknodaohn' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by baing** [comment]
解决了？加油。。
